Fixes #13: Spring Framework Kata update to Spring 6.0.8 and Java 17.
BNYMellon/spring-kata pull request #14
Opened 2023-05-10 17:57 UTC by cguntur-bnym

Associated changes to dependencies and imports.

2023-05-15 21:22 UTC, donraab requested changes
Hi @cguntur-bnym, the changes look good to me, but I have a couple of minor questions inline. Thanks!

2023-05-15 21:22 UTC, donraab commented on spring-framework/pom.xml
>          <!-- The properties below ensure that the code is picked up and compiled as Java 11 -->
Should this comment be updated to Java 17?

2023-05-15 21:22 UTC, donraab commented on spring-framework/ch08_spring-rest/pom.xml
>          <maven.compiler.source>11</maven.compiler.source>
Should source and target now be 17 instead of 11 here?

2023-07-27 02:07 UTC, prathasirisha approved these changes

2023-07-27 16:39 UTC, cguntur-bnym commented
Can someone merge this, please?

2023-07-27 16:56 UTC, merged